name = "Markdown"
path_suffixes = ["md", "mdx"]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "<", end = ">", close = true, newline = true },
    { start = "\"", end = "\"", close = false, newline = false },
    { start = "'", end = "'", close = false, newline = false },
    { start = "`", end = "`", close = false, newline = false },
]
